### ISSUE TITLE
Refined Storage auto-crafting with fluids no longer works

### ISSUE THREAD

**Issue by BubbaVB** [FTBTeam/FTB-Presents-Direwolf20-1.12#39]
* **Modpack Version**: 2.2.0

* **Issue**: Prior to the release of 2.2.0 I was able to auto-craft with fluids stored in Refined Storage.  I have completely rebuilt the crafting pattern and this did not help resolve the issue.  I know there were upgrades to Refined Storage that is in the version so this may be an issue specifically with that mod.

* **Link to Log or Crash File Paste**: This issue did not cause a crash so no file is available.

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Refined Storage version 1.6

* **Known Fix**:

**Comment by tconnard** [comment]
Isn't fluid auto-crafting added in 1.6.1?
It would be nice to have this though.

**Comment by SnowShock35** [comment]
Hello,

Thank you for your contribution to the FTB Presents Direwolf20 1.12 mod-pack. Your involvement greatly helps to improve the quality of the product and keep it bug-free and more enjoyable for everyone. Without your input, the pack would cease to be as good as it is. 

I am delighted to inform you that this issue has been addressed in the recent development of the mod-pack and will be fixed as of version 2.3.0, which will be released publically in the near future. 

As such this issue will now be marked for closure until the update is released and will be closed shortly following its release.

Many thanks once again for your engagement here on the FTBTeam's GitHub.

**SnowShock35 ☃️**

***

> ![SnowShock35](https://cdn.snowshock35.com/avatar-rounded.png)
> ### SnowShock35
> @FTBTeam Pack Developer, Aspiring Full-Stack Engineer, 
> UoN Student, Mod & Modpack Developer, Casual Gamer,
> Nerd, Tea Drinker, Made in the UK 🏳️‍🌈

**Comment by SnowShock35** [comment]
Fixed in [2.3.0](https://www.feed-the-beast.com/projects/ftb-presents-direwolf20-1-12/files/2615409)

**Comment by BubbaVB** [comment]
Can this ticket be reopened or do I need to submit a new ticket?  The issue still exists in the 2.3.0 version of the mod pack.  I tested this in a completely new world.
